config/routes.rb
DealerApp::Application.routes.draw do
  
  root to: "home#index"

  resources :cars

  resources :customers

  resources :managers

  resources :dealers

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  attr_accessible :email, :encrypted_password, :fired, :lastname, :name, :dealer_id, :customers_attributes
  belongs_to :dealer
  has_many :customers

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  # GET /managers
  # GET /managers.json
  def index
    @managers = Dealer.current.managers.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @managers }
    end
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
    @manager = Manager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/new
  # GET /managers/new.json
  def new
    @manager = Manager.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/1/edit
  def edit
    @manager = Manager.find(params[:id])
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Dealer.current.managers.new(params[:manager])

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render json: @manager, status: :created, location: @manager }
      else
        format.html { render action: "new" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /managers/1
  # PUT /managers/1.json
  def update
    @manager = Manager.find(params[:id])

    respond_to do |format|
      if @manager.update_attributes(params[:manager])
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager = Manager.find(params[:id])
    @manager.destroy

    respond_to do |format|
      format.html { redirect_to managers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.slim
= form_for @manager, html: {role: "form", class: "left"} do |f|
  .row
    .col-md-12
      - if @manager.errors.any?
        #error_explanation
          ul
            - @manager.errors.full_messages.each do |message|
              li.text-danger = message
    .col-md-4
      .form-group
        = f.label :name, class: "control-label"
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :lastname, class: "control-label"
        = f.text_field :lastname, class: "form-control"
      .form-group
        = f.label :email, class: "control-label"
        = f.text_field :email, class: "form-control"
      .checkbox
        label
          = f.check_box :fired
          | Fired
      .form-group
        = f.label :encrypted_password, class: "control-label"
        = f.text_field :encrypted_password, class: "form-control"
        
  .row
    .col-md-12
      .actions = f.submit 'Save', class: "btn btn-primary"

app/views/managers/_table.html.slim
table.manager-table.table.table-hover
  thead
    tr
      th №
      th Name
      th Lastname
      th Email
      th Fired
      th
      th
      th
  tbody
    - managers.each_with_index do |manager, i|
      tr
        td = (i+1)
        td = manager.name
        td = manager.lastname
        td = manager.email
        td = manager.fired
        td = link_to 'Show', manager
        td = link_to 'Edit', edit_manager_path(manager)
        td = link_to 'Destroy', manager, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/managers/edit.html.slim
h1 Editing manager

== render 'form'

=' link_to 'Show', @manager
'|
= link_to 'Back', managers_path

app/views/managers/index.html.slim
h1 Listing managers

ul.list-inline
  li
    a.filter href="#all" All
  li
    a.filter href="#fired" Fired
  li
    a.filter href="#not_fired" Not fired

table.table.table-hover.filtered.colored-table
  thead
    tr
      th №
      th Name
      th Lastname
      th Email
      th Fired
      th
      th
      th

  tbody
    - @managers.each_with_index do |manager, i|
      tr
        td = (i+1)
        td = manager.name
        td = manager.lastname
        td = manager.email
        td = manager.fired
        td = link_to 'Show', manager
        td = link_to 'Edit', edit_manager_path(manager)
        td = link_to 'Destroy', manager, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Manager', new_manager_path, class: "btn btn-primary"

app/views/managers/new.html.slim
h1 New manager

= render 'form'

= link_to 'Back', managers_path

app/views/managers/show.html.slim
- if not notice.nil?
  p.bg-info = notice

p
  strong Name:
  = @manager.name
p
  strong Lastname:
  = @manager.lastname
p
  strong Email:
  = @manager.email

=' link_to 'Edit', edit_manager_path(@manager)
'|
= link_to 'Back', managers_path