config/routes.rb
DealerApp::Application.routes.draw do
  
  root to: "home#index"

  resources :cars

  resources :customers

  resources :managers

  resources :dealers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :email, :name, :lastname, 
    :phone_prefix, :phone_code, :phone,
    :comment, :manager_id, :cars_attributes, :status_id

  has_many :cars
  belongs_to :manager
  belongs_to :status

  accepts_nested_attributes_for :cars

  validates :email, presence: true
  validates :manager_id, presence: true

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Dealer.current.customers

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Dealer.current.customers.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper

  def managers_for_select
    Dealer.current.managers.where(fired: false).map { |manager| [fullname(manager), manager.id] }
  end

  def fullname(user)
    "#{user.name} #{user.lastname}"
  end

  def car_for_select
    Dealer.current.cars.where(customer_id: [nil, @customer.id]).map { |car| [car.model, car.id] }
  end

  def status_for_select
    Status.all.map { |s| [s.name, s.id] }
  end

end

app/views/customers/_form.html.slim
= nested_form_for @customer, html: {role: "form", class: "left"} do |f|
  .row
    .col-md-12
      - if @customer.errors.any?
        #error_explanation
          ul.bg-danger
            - @customer.errors.full_messages.each do |message|
              li = message
    .col-md-4
      .form-group
        = f.label :name, class: "control-label"
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :lastname, class: "control-label"
        = f.text_field :lastname, class: "form-control"
      .form-group
        = f.label :email, class: "control-label"
        = f.text_field :email, type: "email", class: "form-control"
      .form-group
        = f.label :phone, class: "control-label"
        .form-inline
          =' f.text_field :phone_prefix, class: "form-control"
          |(
          = f.text_field :phone_code, class: "form-control"
          |) 
          = f.text_field :phone, type: "tel", class: "form-control"
    .col-md-4
      .form-group
        = f.label :comment, class: "control-label"
        = f.text_area :comment, rows: 5, class: "form-control", placeholder: "Please input comment"
      .form-group
        = f.label :manager_id, class: "control-label"
        = f.select :manager_id, managers_for_select, {}, class: "form-control"
      .form-group
        = f.label :status_id, class: "control-label"
        = f.select :status_id, status_for_select, {}, class: "form-control"

    .col-md-4
      = f.label :cars
      
      /ol class="list-unstyled"
      /  - @customer.cars.each do |car|
      /    li = car.model

      = f.fields_for :cars do |car_form|
        =' car_form.select :brand_id, car_for_select
        = car_form.link_to_remove "Remove"
      = f.link_to_add "Add a car", :cars

      /= f.fields_for :cars do |car_form|
      /  =' car_form.select :brand_id, options_from_collection_for_select(Dealer.current.cars.where(customer_id: [nil, @customer.id]), :id, :model)
      /  = car_form.link_to_remove "Remove"
      /= f.link_to_add "Add a car", :cars


      /= f.fields_for :cars do |car|
      /    =' car.text_field :model, disabled: true
      /    = car.link_to_remove "Remove"
      /= f.link_to_add "Add a car", :cars
      

  .row
    .col-md-12  
      =' f.submit 'Save', class: "btn btn-primary"

app/views/customers/edit.html.slim
h1 Editing customer

== render 'form'

=' link_to 'Show', @customer
'|
= link_to 'Back', customers_path

app/views/customers/index.html.slim
h1 Listing customers

ul.list-inline
  li
    a.filter href="#all" All  
  li
    a.filter href="#pending" Pending
  li
    a.filter href="#contract" Contract
  li
    a.filter href="#sale" Sale

table.table.table-hover.filtered.colored-table
  thead
    tr
      th Name
      th Lastname
      th Email
      th colspan=3 Phone 
      th Comment
      th Status
      th
      th
      th

  tbody
    - @customers.each do |customer|
      tr
        td = customer.name
        td = customer.lastname
        td = customer.email
        td = customer.phone_prefix
        td = "(#{customer.phone_code})"
        td = customer.phone
        td = customer.comment
        td = customer.status.name
        td = link_to 'Show', customer
        td = link_to 'Edit', edit_customer_path(customer)
        td = link_to 'Destroy', customer, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Customer', new_customer_path, class: "btn btn-primary"

app/views/customers/new.html.slim
h2 New customer

==render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.slim
- if not notice.nil?
  p.bg-info = notice
  
p
  strong Name:
  = @customer.name
p
  strong Lastname:
  = @customer.lastname
p
  strong Email:
  = @customer.email
p
  strong Phone:
  = @customer.phone
p
  strong Phone code:
  = @customer.phone_code
p
  strong Comment:
  = @customer.comment
p
  strong Manager_id:
  = @customer.manager_id

=' link_to 'Edit', edit_customer_path(@customer)
'|
= link_to 'Back', customers_path