config/routes.rb
DealerApp::Application.routes.draw do
  
  root to: "home#index"

  resources :cars

  resources :customers

  resources :managers

  resources :dealers

end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
  attr_accessible :address, :phone, :site, :title
  has_many :cars
  has_many :managers
  has_many :customers, through: :managers

  def self.current
    Dealer.find(1)
  end
  
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  # GET /dealers
  # GET /dealers.json
  def index
    @dealers = Dealer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dealers }
    end
  end

  # GET /dealers/1
  # GET /dealers/1.json
  def show
    @dealer = Dealer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dealer }
    end
  end

  # GET /dealers/new
  # GET /dealers/new.json
  def new
    @dealer = Dealer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dealer }
    end
  end

  # GET /dealers/1/edit
  def edit
    @dealer = Dealer.find(params[:id])
  end

  # POST /dealers
  # POST /dealers.json
  def create
    @dealer = Dealer.new(params[:dealer])

    respond_to do |format|
      if @dealer.save
        format.html { redirect_to @dealer, notice: 'Dealer was successfully created.' }
        format.json { render json: @dealer, status: :created, location: @dealer }
      else
        format.html { render action: "new" }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dealers/1
  # PUT /dealers/1.json
  def update
    @dealer = Dealer.find(params[:id])

    respond_to do |format|
      if @dealer.update_attributes(params[:dealer])
        format.html { redirect_to @dealer, notice: 'Dealer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealers/1
  # DELETE /dealers/1.json
  def destroy
    @dealer = Dealer.find(params[:id])
    @dealer.destroy

    respond_to do |format|
      format.html { redirect_to dealers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/dealers/_form.html.slim
= form_for @dealer do |f|
  - if @dealer.errors.any?
    #error_explanation
      ul
        - @dealer.errors.full_messages.each do |message|
          li.text-danger = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :site
    = f.text_field :site
  .actions = f.submit 'Save'

app/views/dealers/edit.html.slim
h1 Editing dealer

== render 'form'

= link_to 'Show', @dealer
'|
= link_to 'Back', dealers_path

app/views/dealers/index.html.slim
h1 Listing dealers

table.table.table-hover
  thead
    tr
      th Title
      th Address
      th Phone
      th Site
      th
      th
      th
  tbody
    - @dealers.each do |dealer|
      tr
        td = dealer.title
        td = dealer.address
        td = dealer.phone
        td = dealer.site
        td = link_to 'Show', dealer
        td = link_to 'Edit', edit_dealer_path(dealer)
        td = link_to 'Destroy', dealer, data: {:confirm => 'Are you sure?'}, :method => :delete
br
= link_to 'New Dealer', new_dealer_path, class: "btn btn-primary"

app/views/dealers/new.html.slim
h1 New dealer

== render 'form'

= link_to 'Back', dealers_path

app/views/dealers/show.html.slim
- if not notice.nil?
  p.bg-info = notice
  
p
  strong Title:
  = @dealer.title
p
  strong Address:
  = @dealer.address
p
  strong Phone:
  = @dealer.phone
p
  strong Site:
  = @dealer.site

= link_to 'Edit', edit_dealer_path(@dealer)
'|
= link_to 'Back', dealers_path