config/routes.rb
DealerApp::Application.routes.draw do
  
  root to: "home#index"

  resources :cars

  resources :customers

  resources :managers

  resources :dealers

end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :model, :vin, :brand_id, :id, :brand_attributes
  belongs_to :customer
  belongs_to :dealer
  belongs_to :brand

  validates :brand, presence: true
  validates :dealer, presence: true

  accepts_nested_attributes_for :brand

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Dealer.current.cars

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Dealer.current.cars.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new
    @brands = Brand.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
    @brands = Brand.all
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Dealer.current.cars.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper

  def brands_for_option
    Brand.All
  end

end

app/views/cars/_form.html.slim
= nested_form_for @car do |f|
  - if @car.errors.any?
    #error_explanation
      ul.bg-danger
        - @car.errors.full_messages.each do |message|
          li = message
  .row
    .col-md-4
      .form-group
        = f.label :model, class: "control-label"
        = f.text_field :model, class: "form-control"
      .form-group
        = f.label :vin, class: "control-label"
        = f.text_field :vin, class: "form-control"
      .form-group
        = f.label :brand_id
        = f.select :brand_id, options_from_collection_for_select(@brands, :id, :name, @car.brand_id), {}, class: "form-control"

        /= f.text_field :brand, class: "form-control"
        /input id="brand" list="brands_list" name="car[brand_id]" class="form-control"
        /datalist id="brands_list"
        /  - Brand.all do |b|
        /    option = b.name

  .row
    .col-md-12
      .actions = f.submit 'Save', class: "btn btn-primary"

app/views/cars/edit.html.slim
h1 Editing car

== render 'form'

= link_to 'Show', @car
'|
= link_to 'Back', cars_path

app/views/cars/index.html.slim
h1 Listing cars

table.table.table-hover
  thead
    tr
      th Brand
      th Model
      th Vin
      th Dealer
      th Customer
      th
      th
      th

  tbody
    - @cars.each do |car|
      tr
        td = car.brand.name
        td = car.model
        td = car.vin
        td = car.dealer.title
        td = car.customer_id
        td = link_to 'Show', car
        td = link_to 'Edit', edit_car_path(car)
        td = link_to 'Destroy', car, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Car', new_car_path, class: "btn btn-primary"

app/views/cars/new.html.slim
h1 New car
.aa = @cars 
== render 'form'

= link_to 'Back', cars_path

app/views/cars/show.html.slim
- if not notice.nil?
  p.bg-info = notice
  
p
  strong Model:
  = @car.model
p
  strong Vin:
  = @car.vin

= link_to 'Edit', edit_car_path(@car)
'|
= link_to 'Back', cars_path